#!/usr/bin/env python3
"""Check the window actually works, without a phone or a mouse.

Drives the real MainWindow against a *synthetic* library and a directory "device",
presses Sync, and checks what comes back. Renders the window to ~/mika/tmp so a
human can look at it.

    python3 tests/gui_smoke.py

Three rules this file exists to enforce:

1. **It never points at the real library**, and XDG_CONFIG_HOME points at the
   fixture, so the suite can't read the real config either. An earlier version
   pressed Sync against `music (compressed)` and copied all 27 GB of it into the
   scratch directory. The window was right; the test was the mutator.
2. **The Settings panel round-trips** — a save writes the config file, and the
   window then works from the file alone with no command-line overrides.
3. **A first run says what to do** rather than showing an empty table.
"""

from __future__ import annotations

import json
import os
import shutil
import sys
import time
from pathlib import Path

os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")

HERE = Path(__file__).resolve().parent
PROJECT = HERE.parent
sys.path.insert(0, str(PROJECT))
sys.path.insert(0, str(HERE))

SCRATCH = Path.home() / "mika" / "tmp" / "gui-smoke"
# before anything imports marimo-sync's config, so config_path() lands in the fixture
os.environ["XDG_CONFIG_HOME"] = str(SCRATCH / "xdg-config")
os.environ["XDG_CACHE_HOME"] = str(SCRATCH / "xdg-cache")

import fixture  # noqa: E402

LIB = SCRATCH / "lib"
DEV = SCRATCH / "device"
CONFIG = SCRATCH / "config.json"
SHOT = Path.home() / "mika" / "tmp" / "marimo-sync-window.png"
SERVE_PORT = 8477          # fixed so the test can look for a listener
HERE_FIXTURE_SRC = SCRATCH / "flac"      # stand-in for ~/Music: never the real one
STUB_CONVERT = SCRATCH / "stub-convert.py"


def wait_for_port(app, port: int, want_open: bool, timeout: float = 15.0) -> bool:
    """Wait for a listener, pumping Qt's event loop as we go.

    Without the pumping, `QTimer.singleShot` never fires and QProcess signals are
    never delivered -- so this waited 20 seconds for a server that had never been
    asked to start, and the check that followed found a token generated by an
    earlier window and called it proof."""
    import socket
    t0 = time.monotonic()
    while time.monotonic() - t0 < timeout:
        app.processEvents()
        s = socket.socket()
        s.settimeout(0.3)
        open_now = s.connect_ex(("127.0.0.1", port)) == 0
        s.close()
        if open_now == want_open:
            return True
        time.sleep(0.2)
    return False


def health(port: int, token: str | None = None) -> tuple[int, bytes]:
    import urllib.request
    url = f"http://127.0.0.1:{port}/api/health"
    req = urllib.request.Request(url)
    if token:
        req.add_header("X-Marimo-Token", token)
    try:
        with urllib.request.urlopen(req, timeout=5) as r:
            return r.status, r.read()
    except Exception as e:
        return getattr(e, "code", 0), str(e).encode()

FAILED: list[str] = []
N = 0


def check(name: str, ok: bool, detail: str = "") -> None:
    global N
    N += 1
    print(f"  {'PASS' if ok else 'FAIL'}  {name}" + (f"  -- {detail}" if detail and not ok else ""))
    if not ok:
        FAILED.append(name)


def pump(app, cond, timeout: float = 90.0, what: str = "") -> bool:
    """Spin the event loop until cond() is true (QProcess signals need it)."""
    t0 = time.monotonic()
    while time.monotonic() - t0 < timeout:
        app.processEvents()
        if cond():
            return True
        time.sleep(0.05)
    print(f"    (timed out waiting for {what})")
    return False


def device_files() -> set[str]:
    return {str(p.relative_to(DEV)) for p in DEV.rglob("*") if p.is_file()}


def main() -> int:
    if SCRATCH.exists():
        shutil.rmtree(SCRATCH)
    SCRATCH.mkdir(parents=True)
    albums = fixture.build_library(LIB)
    DEV.mkdir(parents=True)
    fixture.copy_album(LIB / albums[0], DEV / albums[0])
    fixture.ghost_album(DEV)
    CONFIG.write_text(json.dumps({
        "source": str(LIB),
        "device": f"dir:{DEV}",
        # Hermetic: the bundled converter would otherwise be run with its default
        # source of ~/Music and this fixture as the destination -- i.e. the test
        # would convert her real albums into scratch. Both sides point at fixtures.
        "flac_source": str(HERE_FIXTURE_SRC),
        "convert_script": str(STUB_CONVERT),
        "wave_script": "none",
        "serve": {"port": SERVE_PORT, "auto": True},
    }))
    check("the fixture starts with no token, so the window has to make one",
          not (json.loads(CONFIG.read_text()).get("serve") or {}).get("token"))

    fixtures = HERE_FIXTURE_SRC
    fixtures.mkdir(parents=True)
    (fixtures / "Nobody - (2024) A Fixture Album [FLAC]").mkdir()
    (fixtures / "Nobody - (2024) A Fixture Album [FLAC]" / "01. Fixture.flac").write_bytes(b"x")
    STUB_CONVERT.write_text("#!/usr/bin/env python3\n"
                            "import sys\n"
                            "print('stub converter:', ' '.join(sys.argv[1:]))\n")
    STUB_CONVERT.chmod(0o755)

    from PyQt6.QtWidgets import QApplication
    import marimosync.gui as gui

    asked = []
    real_exec = gui.QMessageBox.exec

    def fake_exec(self):
        asked.append(self.text())
        return gui.QMessageBox.StandardButton.Cancel

    gui.QMessageBox.exec = fake_exec

    app = QApplication([])
    print("window: starting against the fixture library and device\n")
    w = gui.MainWindow(["--config", str(CONFIG), "--source", str(LIB), "--device", f"dir:{DEV}"])
    w.show()

    got = pump(app, lambda: w.last_plan is not None, 60, "the first plan")
    check("the window reaches the tool and gets a plan back", got)
    if not got:
        return 1

    plan = w.last_plan
    check("header shows the library", str(len(albums)) in w.lbl_lib.text(), w.lbl_lib.text())
    check("header shows the device", "dir:" in w.lbl_dev.text(), w.lbl_dev.text())
    check("the fixture is seen as needing work", plan["push_files"] > 0, str(plan["push_files"]))
    check("the orphan is seen", plan["orphan_files"] == 1, str(plan["orphan_files"]))
    check("the table hides what's already fine", w.table.rowCount() == plan["albums_total"] - 1,
          f"{w.table.rowCount()} rows for {plan['albums_total']} albums")
    check("no setup complaint while things are configured", not w.setup_note, str(w.setup_note))

    w.cb_all.setChecked(True)
    check("show-all reveals every album", w.table.rowCount() == plan["albums_total"],
          f"{w.table.rowCount()} rows")
    w.cb_all.setChecked(False)
    w.search.setText("ghost")
    check("the name filter works", w.table.rowCount() == 1, f"{w.table.rowCount()} rows")
    w.search.clear()

    print("\nwindow: pressing Sync on a small push\n")
    before = device_files()
    w.btn_sync.click()
    check("Sync launches the tool", pump(app, lambda: w.proc is not None, 10, "the sync to start"))
    check("a small push doesn't interrupt with a dialog", not asked, str(asked))
    check("Sync finishes", pump(app, lambda: w.proc is None, 180, "the sync to finish"))
    back = pump(app, lambda: w.last_plan is not None and w.last_plan["push_files"] == 0, 60,
                "the refreshed plan")
    check("nothing left to push", back, str(w.last_plan and w.last_plan["push_files"]))
    check("the rescan reminder survived the refresh", "rescan" in w.banner.text(), w.banner.text())
    check("Sync button is back to plain Sync", w.btn_sync.text() == "Sync", w.btn_sync.text())
    check("the log has no raw escape codes in it", "\x1b" not in w.log.toPlainText(),
          repr(w.log.toPlainText()[:80]))
    check("the device gained the album and lost nothing", device_files() > before,
          f"{len(before)} -> {len(device_files())}")

    w.grab().save(str(SHOT))
    print(f"\nwindow rendered to {SHOT}")

    print("\nwindow: Prepare runs the local stages\n")
    w.action_note = None
    w.btn_prepare.click()
    check("Prepare launches the tool", pump(app, lambda: w.proc is not None, 10, "prepare to start"))
    check("with the local-only command", "--prepare" in w.log.toPlainText(),
          w.log.toPlainText()[-220:])
    check("Prepare finishes", pump(app, lambda: w.proc is None, 60, "prepare to finish"))

    print("\nwindow: the Settings panel round-trips\n")
    real_dialog_exec = gui.QDialog.exec
    gui.QDialog.exec = lambda self: gui.QDialog.DialogCode.Accepted     # don't block on it
    w.open_settings()
    gui.QDialog.exec = real_dialog_exec
    check("saving wrote the config file", CONFIG.is_file())
    saved = json.loads(CONFIG.read_text())
    check("it kept the paths it was showing", saved.get("source") == str(LIB)
          and saved.get("device") == f"dir:{DEV}", str(saved))
    check("saving dropped the command-line overrides",
          gui.overrides_in(w.argv) == [], " ".join(w.argv))
    check("and the window still works from the file alone",
          pump(app, lambda: w.last_plan is not None and not w.proc, 60, "a plan after settings")
          and w.last_plan["albums_total"] == len(albums) + 1,
          str(w.last_plan and w.last_plan["albums_total"]))

    print("\nwindow: a first run says what to do\n")
    fresh = gui.MainWindow(["--config", str(SCRATCH / "empty-config.json"),
                            "--source", str(SCRATCH / "no-such-library"),
                            "--device", f"dir:{DEV}"])
    fresh.show()
    pump(app, lambda: fresh.last_plan is not None, 60, "the first-run plan")
    check("it explains the missing library", fresh.setup_note and "Settings" in fresh.setup_note,
          str(fresh.setup_note))
    check("and the banner carries it", "Settings" in fresh.banner.text(), fresh.banner.text())
    on_device_albums = {str(p.relative_to(DEV)).split("/")[0] for p in DEV.rglob("*") if p.is_file()}
    check("with no library, what's on the device reads as device-only",
          fresh.table.rowCount() == len(on_device_albums),
          f"{fresh.table.rowCount()} rows for {len(on_device_albums)} device albums")
    fresh.close()

    print("\nwindow: a rename is shown, not crashed on\n")
    renamed = "Synthetic Band — (2021) First Light [OPUS]"
    shutil.move(LIB / albums[0], LIB / renamed)
    w.refresh(log=True)
    pump(app, lambda: w.last_plan is not None and w.last_plan["renames"] >= 1, 60, "a rename")
    check("the plan counts it as a rename", bool(w.last_plan and w.last_plan["renames"] >= 1),
          str(w.last_plan and w.last_plan.get("renames")))
    statuses = {w.table.item(r, 2).text() for r in range(w.table.rowCount())}
    check("the row reads as a rename", "same album, old name" in statuses, str(statuses))
    check("and the header mentions the saving",
          "already there" in w.lbl_total.text(), w.lbl_total.text())

    print("\nwindow: a big push asks first, and cancelling stops it\n")
    missing = DEV / albums[0] / "waves.marimo"
    if missing.exists():
        missing.unlink()
    w.refresh(log=True)
    pump(app, lambda: w.last_plan is not None and w.last_plan["push_files"] >= 1, 30, "work to push")
    check("there is work to push again", bool(w.last_plan and w.last_plan["push_files"] >= 1),
          str(w.last_plan and w.last_plan["push_files"]))
    gui.CONFIRM_FILES = 0
    frozen = device_files()
    w.btn_sync.click()
    app.processEvents()
    time.sleep(0.3)
    app.processEvents()
    check("the confirmation appeared", len(asked) > 0, str(asked))
    check("cancelling started no process", w.proc is None)
    check("cancelling changed nothing on the device", device_files() == frozen)
    gui.CONFIRM_FILES = 100

    gui.QMessageBox.exec = real_exec
    w.close()
    app.processEvents()
    check("closing the window leaves nothing running", w.proc is None)

    print("\nwindow: it serves to the phone while it is open\n")
    # a window of its own: the one above has already been closed, and closing is
    # exactly the behaviour this section checks at the end
    w2 = gui.MainWindow(["--config", str(CONFIG)])
    w2.show()
    served = wait_for_port(app, SERVE_PORT, want_open=True, timeout=20)
    check(f"a server is listening on {SERVE_PORT} once the window is open", served)
    check("and the window knows it started one", w2.serve_proc is not None)
    if served:
        code, body = health(SERVE_PORT)
        check("and it refuses an unknown caller", code == 401, f"{code} {body[:60]}")
    saved = (json.loads(CONFIG.read_text()).get("serve") or {}).get("token")
    check("a token is written down, so the phone's saved one keeps working",
          bool(saved) and len(saved) == 12, str(saved))
    if saved:
        code, body = health(SERVE_PORT, token=saved)
        check("and the server wants that one", code == 200 and b"marimo-sync" in body,
              f"{code} {body[:60]}")
    check("the label names the address it is serving on",
          bool(w2.serve_url) and w2.serve_url in w2.lbl_serve.text(), w2.lbl_serve.text())

    w2.close()
    app.processEvents()
    gone = wait_for_port(app, SERVE_PORT, want_open=False, timeout=10)
    check("closing the window stops the server", gone)

    print()
    if FAILED:
        print(f"{len(FAILED)}/{N} checks FAILED: " + ", ".join(FAILED))
        return 1
    print(f"all {N} checks passed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
